// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Ability struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type Allegiance struct {
	ID            string  `json:"id"`
	Name          string  `json:"name"`
	Description   *string `json:"description,omitempty"`
	GrandAlliance *string `json:"grandAlliance,omitempty"`
	MortalRealm   *string `json:"mortalRealm,omitempty"`
}

type AllegianceFilters struct {
	Name          *string `json:"name,omitempty"`
	GrandAlliance *string `json:"grandAlliance,omitempty"`
	Limit         *int    `json:"limit,omitempty"`
	Offset        *int    `json:"offset,omitempty"`
}

type DamageTable struct {
	ID                 string  `json:"id"`
	WoundTrackPosition *int    `json:"woundTrackPosition,omitempty"`
	Move               *string `json:"move,omitempty"`
	MinWoundsSuffered  *int    `json:"minWoundsSuffered,omitempty"`
}

type GrandAlliance struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

type Query struct {
}

type Unit struct {
	ID               string         `json:"id"`
	Name             string         `json:"name"`
	Allegiance       *string        `json:"allegiance,omitempty"`
	GrandAlliance    *string        `json:"grandAlliance,omitempty"`
	Champion         *string        `json:"champion,omitempty"`
	Size             *string        `json:"size,omitempty"`
	Move             *string        `json:"move,omitempty"`
	Description      *string        `json:"description,omitempty"`
	Save             *int           `json:"save,omitempty"`
	Bravery          *int           `json:"bravery,omitempty"`
	Models           *int           `json:"models,omitempty"`
	Points           *int           `json:"points,omitempty"`
	Wounds           *int           `json:"wounds,omitempty"`
	Abilities        []*Ability     `json:"abilities,omitempty"`
	Keywords         []*string      `json:"keywords,omitempty"`
	CommandAbilities []*Ability     `json:"commandAbilities,omitempty"`
	Magic            []*Ability     `json:"magic,omitempty"`
	DamageTable      []*DamageTable `json:"damageTable,omitempty"`
	MissileWeapons   []*Weapon      `json:"missileWeapons,omitempty"`
	MeleeWeapons     []*Weapon      `json:"meleeWeapons,omitempty"`
}

type UnitFilters struct {
	Name          *string `json:"name,omitempty"`
	GrandAlliance *string `json:"grandAlliance,omitempty"`
	GrandStrategy *string `json:"grandStrategy,omitempty"`
	Points        *int    `json:"points,omitempty"`
	Limit         *int    `json:"limit,omitempty"`
	Offset        *int    `json:"offset,omitempty"`
}

type User struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Warscroll struct {
	ID              string  `json:"id"`
	Name            string  `json:"name"`
	AllegianceID    *string `json:"allegianceId,omitempty"`
	GrandAllianceID *string `json:"grandAllianceId,omitempty"`
	Size            *int    `json:"size,omitempty"`
	Points          *int    `json:"points,omitempty"`
	BattlefieldRole *string `json:"battlefieldRole,omitempty"`
	Notes           *string `json:"notes,omitempty"`
}

type WarscrollFilters struct {
	Name            *string `json:"name,omitempty"`
	Points          *int    `json:"points,omitempty"`
	BattlefieldRole *string `json:"battlefieldRole,omitempty"`
	Size            *string `json:"size,omitempty"`
	Notes           *string `json:"notes,omitempty"`
	Limit           *int    `json:"limit,omitempty"`
	Offset          *int    `json:"offset,omitempty"`
}

type Weapon struct {
	ID      string  `json:"id"`
	Name    string  `json:"name"`
	Range   *string `json:"range,omitempty"`
	Attacks *string `json:"attacks,omitempty"`
	ToHit   *string `json:"toHit,omitempty"`
	ToWound *string `json:"toWound,omitempty"`
	Rend    *string `json:"rend,omitempty"`
	Damage  *string `json:"damage,omitempty"`
}
